version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kroot_db
    restart: always
    environment:
      POSTGRES_USER: kroot_admin
      POSTGRES_PASSWORD: kroot_password
      POSTGRES_DB: kroot_db
    ports:
      - "5433:5432"
    volumes:
      - kroot_postgres_data:/var/lib/postgresql/data

volumes:
  kroot_postgres_data: